name: release

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false

      - run: sudo apt install -y p7zip-full

      - uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v6.0.0
        with:
          python-version-file: ".python-version"

      - uses: astral-sh/setup-uv@85856786d1ce8acfbcc2f13a5f3fbd6b938f9f41 # v7.1.2

      - run: uv run main.py
        id: check

      - uses: ncipollo/release-action@b7eabc95ff50cbeeedec83973935c8f306dfcd0b # v1.20.0
        if: steps.check.outputs.updated == 'true'
        with:
          tag: v${{ steps.check.outputs.version }}
          name: WeChat Windows Version ${{ steps.check.outputs.version }}
          artifacts: build/weixin_${{ steps.check.outputs.version }}.exe
          bodyFile: build/releaseNote.md
          immutableCreate: true
